/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package id2212.hw1.client.view;

import id2212.hw1.client.EventEnum;
import id2212.hw1.client.EventEnum;
import id2212.hw1.client.Session;
import id2212.hw1.client.Session;
import id2212.hw1.packets.DataPacket;
import id2212.hw1.packets.ResponsePacket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alfredo
 */
public class MainPanel extends GenericPanel {
    private Session session;

    /**
     * Creates new form MainPanel
     */
    public MainPanel(Session s) {
        this.session=s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentWordLabel = new javax.swing.JLabel();
        letterTextField = new javax.swing.JTextField();
        sendLetterButton = new javax.swing.JButton();
        counterLabel = new javax.swing.JLabel();

        currentWordLabel.setText("____________");

        letterTextField.setText("letter");

        sendLetterButton.setText("send letter");
        sendLetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLetterButtonActionPerformed(evt);
            }
        });

        counterLabel.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendLetterButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(counterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(letterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentWordLabel)
                    .addComponent(letterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(counterLabel)
                .addGap(18, 18, 18)
                .addComponent(sendLetterButton)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendLetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendLetterButtonActionPerformed
        try {
            // TODO add your handling code here:

            session.getCurrentMatch().guessALetter(this.letterTextField.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please insert one letter only");
        }
    
        
    }//GEN-LAST:event_sendLetterButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel counterLabel;
    private javax.swing.JLabel currentWordLabel;
    private javax.swing.JTextField letterTextField;
    private javax.swing.JButton sendLetterButton;
    // End of variables declaration//GEN-END:variables


    @Override
    public void updateView(EventEnum e) {
        
        if(e==EventEnum.GAMERESPONSE){
            ResponsePacket lastReply = session.getCurrentMatch().getLastReply();
            this.currentWordLabel.setText(lastReply.getCurrentWordView());
            this.counterLabel.setText(session.getCurrentMatch().getLastReply().getFailedAttemptsCounter().toString());
            
        }
        
    }
}
